[package]
name = "kleinian-cli"
version = "0.1.0"
authors = ["Daniel R Gulotta <dgulotta@alum.mit.edu>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
clap = "4.5"
image = { version = "0.25", features = ["png"] }
kleinian = { path = "../kleinian" }
