[package]
name = "kleinian-cli"
version = "0.1.0"
authors = ["Daniel R Gulotta <dgulotta@alum.mit.edu>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
clap = "2.33"
image = "0.23"
kleinian = { path = "../kleinian" }
