[package]
name = "kleinian"
version = "0.1.0"
authors = ["Daniel R Gulotta <dgulotta@alum.mit.edu>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
nalgebra = "^0.32"
num-complex = "^0.4"
ordered-float = "^4"
derivative = "^2.2"
